### ISSUE TITLE
it+git//github.com/maxplanck-ie/HiCBrowse@master' does not exist.

### ISSUE THREAD

**Issue by elyas101** [deeptools/HiCBrowser#24]
Hi, 
I would be interested to use HiCBrowser but get this error:

pip install git+git//github.com/maxplanck-ie/HiCBrowse@master

**Invalid requirement: 'git+git//github.com/maxplanck-ie/HiCBrowse@master'
It looks like a path. File 'git+git//github.com/maxplanck-ie/HiCBrowse@master' does not exist.**

**Comment by bgruening** [comment]
Can you try the following?

`pip install git+git//github.com/deeptools/HiCBrowse@master`

**Comment by elyas101** [comment]
Thank you! 
This command worked: 

pip install git+https://github.com/maxplanck-ie/HiCBrowser
